# This file lists tools managed by Aftman, a cross-platform toolchain manager
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
# Rojo enables syncing between your filesystem and Roblox Studio
# Used for live development and building place/model files
rojo = "rojo-rbx/rojo@7.4.3"

# StyLua is an opinionated Lua formatter for enforcing consistent code style
# Formats code according to the Roblox Lua Style Guide with minor deviations
stylua = "JohnnyMorganz/stylua@2.1.0"

# Selene is a blazing-fast modern Lua linter written in Rust
# Provides static analysis and helps catch bugs before runtime
selene = "Kampfkarren/selene@0.28.0"

# Run-in-Roblox enables running scripts inside Roblox Studio from the command line
# Essential for automated testing with TestEZ in CI/CD pipelines
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"